from typing import Annotated

from langgraph.graph import MessagesState
from typing_extensions import TypedDict


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    aggressive_history: Annotated[
        str, "Aggressive Agent's Conversation history"
    ]  # Conversation history
    conservative_history: Annotated[
        str, "Conservative Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_aggressive_response: Annotated[
        str, "Latest response by the aggressive analyst"
    ]  # Last response
    current_conservative_response: Annotated[
        str, "Latest response by the conservative analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    asset_type: Annotated[str, "Asset type under analysis such as stock or crypto"]
    instrument_context: Annotated[str, "Deterministic ticker identity resolved at run start"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Sentiment Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
    past_context: Annotated[str, "Memory log context injected at run start (same-ticker decisions + cross-ticker lessons)"]

    # momentum researcher / thesis fields (Phase 2)
    retorno_12_1: Annotated[float, "12-month buy-and-hold return, skip-month convention (D-07, D-10: computed by Python before the LLM runs)"]
    momentum_z_score: Annotated[float, "Z-score of retorno_12_1 vs its 5-year rolling distribution (D-15: computed by Python)"]
    momentum_valid: Annotated[bool, "False when there is insufficient OHLCV history to compute momentum (fail-open signal, D-10)"]
    confidence_level: Annotated[str, "high|medium|low, derived by Python code from z-score magnitude — never LLM-generated (D-15)"]
    thesis: Annotated[str, "LLM causal-reasoning prose (D-09)"]
    thesis_verdict: Annotated[str, "Buy|Hold|Sell (D-09)"]
    refutation_criterion: Annotated[str, "Concrete falsifiable prediction (D-17)"]
    data_points: Annotated[dict, "LLM-cited numeric values for D-11 validation: retorno_12_1, z_score"]
    verified: Annotated[bool, "D-11 validation result — exact tolerance match between data_points and computed values"]

    # auditor fields (Phase 3 — AUDIT-01/02/03/04)
    auditor_phase1_status: Annotated[str, "pass|fail — pass when auditor_retorno_12_1/auditor_z_score computed successfully, fail when data fetch fails (D-02)"]
    auditor_phase1_failure_reason: Annotated[str, "Empty string when status=pass; otherwise a code like 'insufficient_ohlcv_history' explaining the failure (D-02)"]
    auditor_retorno_12_1: Annotated[float, "Auditor's own computed 12-month momentum (independent of Research retorno_12_1, AUDIT-01)"]
    auditor_z_score: Annotated[float, "Auditor's own computed Z-score (independent of Research momentum_z_score, AUDIT-01)"]
    auditor_confidence_level: Annotated[str, "high|medium|low, derived by Python code from auditor_z_score (AUDIT-02)"]
    auditor_verdict: Annotated[str, "Buy|Hold|Sell|INCONCLUSIVE (AUDIT-02; INCONCLUSIVE when phase1_status=fail, D-02)"]
    auditor_reasoning: Annotated[str, "Auditor's causal reasoning under the asymmetric refutation mandate (D-04): why Research thesis could be WRONG"]
    auditor_refutation_criterion: Annotated[str, "Concrete falsifiable observation disproving the RESEARCH thesis, not the Auditor's own verdict (D-04)"]
    auditor_data_points: Annotated[dict, "Auditor's own cited numeric values: retorno_12_1 and z_score (keyed identically to data_points, AUDIT-01, D-09)"]
    auditor_verified: Annotated[bool, "D-11 validation result — computed deterministically by Python, never self-reported by the LLM (AUDIT-03)"]
    comparison_result: Annotated[str, "match|mismatch|not_reached — thesis_verdict vs auditor_verdict comparison, persisted UNCONDITIONALLY including refuted cycles (D-06)"]

    # risk squad fields (Phase 4 — RISK-01/02/EXEC-01)
    proposed_side: Annotated[str, "Buy|Hold|Sell — deterministically parsed from trader_investment_plan's FINAL TRANSACTION PROPOSAL trailer via parse_trader_action, never re-interpreted by an LLM"]
    portfolio_snapshot_status: Annotated[str, "pass|fail — pass when the Alpaca paper account snapshot (04-02-PLAN.md) succeeds; fail triggers a deterministic veto safety-net regardless of perspective verdicts"]
    portfolio_total_value: Annotated[float, "Alpaca paper account equity, pre-computed by Python — never LLM-estimated, prevents numerical hallucination"]
    existing_position_value: Annotated[float, "Dollar market value of any existing position in company_of_interest on the Alpaca paper account, 0.0 if none"]
    proposed_notional_usd: Annotated[float, "Deterministic dollar sizing proposal = risk_position_size_pct * portfolio_total_value; D-03: this is the size Risk votes on, never modified by any Risk Squad node"]
    risk_concentration_pct: Annotated[float, "(existing_position_value + proposed_notional_usd) / portfolio_total_value; forced to 1.0 when portfolio_snapshot_status=fail — a fail-SAFE sentinel, not a fail-open default"]
    conservative_verdict: Annotated[dict, "RiskDecision.model_dump() from the isolated conservative perspective — D-02: its own field only, never read or written by the other two perspectives"]
    balanced_verdict: Annotated[dict, "RiskDecision.model_dump() from the isolated balanced perspective — D-02: its own field only, never read or written by the other two perspectives"]
    aggressive_verdict: Annotated[dict, "RiskDecision.model_dump() from the isolated aggressive perspective — D-02: its own field only, never read or written by the other two perspectives"]
    final_veto: Annotated[bool, "True if ANY perspective verdict is VETO, OR portfolio_snapshot_status=fail — computed deterministically by risk_aggregator, never by an LLM, D-03/D-04"]
    concentration_verified: Annotated[bool, "True only when all three perspectives' cited_concentration_pct matches risk_concentration_pct within +/-0.005 (0.5pp) — computed deterministically by risk_aggregator, D-11 discipline applied a third time"]
    execution_log: Annotated[list, "Unconditional per-cycle audit trail entries, mirroring the Auditor's D-06 persistence discipline applied to Risk veto/approve cycles"]
    paper_order_id: Annotated[str, "Alpaca paper order id after successful submission (04-02-PLAN.md); empty string if not submitted"]
    paper_execution_status: Annotated[str, "not_attempted|submitted|failed|skipped_hold — set by the Paper Execution node (04-02-PLAN.md), never reachable when final_veto=True, D-04 topology enforced in 04-04-PLAN.md"]
