"""Deterministic parser for trader action (Buy/Hold/Sell) from transaction proposals.

The Trader produces markdown with a deterministic trailing ``FINAL TRANSACTION PROPOSAL``
line that renders the structured action as **BUY/HOLD/SELL**. This module parses that
trailer safely because it is this project's own deterministically-rendered markdown
(not untrusted external text like news/social feeds per CONCERNS.md). This pattern
mirrors rating.py's established safety: parsing a specific trailer is safe when it
originates from this codebase's own render functions.

The parser is used by:
- Risk Squad nodes to extract the proposed_side from trader_investment_plan
- Test infrastructure to validate parse behavior
"""

from __future__ import annotations

import re

# Canonical 3-tier transaction direction used by the Trader.
# (Most bullish to most bearish ordering preserved for consistency.)
TRADER_ACTIONS_3_TIER: tuple[str, ...] = ("Buy", "Hold", "Sell")

_ACTION_SET = {a.lower() for a in TRADER_ACTIONS_3_TIER}

# Matches "FINAL TRANSACTION PROPOSAL: **ACTION**" or "FINAL TRANSACTION PROPOSAL: ACTION"
# Tolerates markdown bold wrappers (**/\*\*) and case-insensitive matching.
_TRANSACTION_PROPOSAL_RE = re.compile(
    r"FINAL\s+TRANSACTION\s+PROPOSAL:\s*\*{0,2}(\w+)\*{0,2}",
    re.IGNORECASE,
)


def parse_trader_action(text: str, default: str = "Hold") -> str:
    """Deterministically extract a 3-tier trader action from transaction proposal text.

    Strategy:
    1. Search for the literal "FINAL TRANSACTION PROPOSAL: **ACTION**" trailer
       (tolerant of markdown bold wrappers and case-insensitive).
    2. Return the Title-cased action if it matches one of the 3 tiers, else default.

    This parser is safe because it targets a deterministic trailer generated by
    this codebase's own render_trader_proposal function (schemas.py), not untrusted
    external text injection risk like news/social feeds (per CONCERNS.md).

    Args:
        text: Markdown or plain text containing a trader proposal
        default: Action to return if no trailer is found or no tier is matched
                 (default: "Hold")

    Returns:
        Title-cased action string: "Buy", "Hold", or "Sell" (or default).
    """
    m = _TRANSACTION_PROPOSAL_RE.search(text)
    if m:
        action_str = m.group(1).lower()
        if action_str in _ACTION_SET:
            return action_str.capitalize()

    return default
